[project]
name = "docs"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "furo==2023.9.10",
    "numpy>=2.1.2",
    "sphinx==7.2.6",
    "sphinx-toolbox==3.5.0",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "tqdm>=4.66.5",
]
